// Exports the EarmarkPockets ABI from Foundry's build output to web/src/abi.ts as a `const`, so viem and wagmi
// infer every function, event and error type. Run from contracts/ after `forge build`: `node script/export-abi.mjs`.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const artifact = resolve(here, '../out/EarmarkPockets.sol/EarmarkPockets.json');
const target = resolve(here, '../../web/src/abi.ts');

const { abi } = JSON.parse(readFileSync(artifact, 'utf8'));
if (!Array.isArray(abi) || abi.length === 0) throw new Error(`No ABI found in ${artifact}`);

const source = `// Generated by contracts/script/export-abi.mjs from Foundry's build output. Do not edit by hand.
export const earmarkAbi = ${JSON.stringify(abi, null, 2)} as const;
`;
writeFileSync(target, source);
console.log(`Wrote ${abi.length} ABI entries to ${target}`);
