// Every user-facing string in Earmark, in British English, following design-system/guidelines/10-content.md.
// Kept in one file so Yoruba, Hausa and Igbo translations can follow (PRD Section 10).
// Never use: gas, transaction, hash, mainnet, sponsor, spender (D1). src/copy.test.ts checks this.

export type PeriodKind = 'day' | 'week' | 'month' | 'other';

const PERIOD_WORD: Record<PeriodKind, string> = {
  day: 'today',
  week: 'this week',
  month: 'this month',
  other: 'this period',
};

const LIMIT_LABEL: Record<PeriodKind, string> = {
  day: 'Daily limit',
  week: 'Weekly limit',
  month: 'Monthly limit',
  other: 'Limit',
};

const EACH_PERIOD: Record<PeriodKind, string> = {
  day: 'a day',
  week: 'a week',
  month: 'a month',
  other: 'each period',
};

export const copy = {
  appName: 'Earmark',

  period: {
    word: (p: PeriodKind) => PERIOD_WORD[p],
    limitLabel: (p: PeriodKind) => LIMIT_LABEL[p],
    each: (p: PeriodKind) => EACH_PERIOD[p],
    options: [
      { value: 'day', label: 'Day' },
      { value: 'week', label: 'Week' },
      { value: 'month', label: 'Month' },
    ],
    resets: (when: string) => `Resets ${when}`,
  },

  nav: {
    label: 'Main',
    pockets: 'Pockets',
    requests: 'Requests',
    activity: 'Activity',
    settings: 'Settings',
    home: 'Home',
    you: 'You',
  },

  poc: {
    title: 'Proof of concept',
    body: 'Use small amounts while Earmark is being tested.',
    testnet: 'You are on Arc testnet, where USDC has no value.',
  },

  system: {
    wrongNetworkTitle: 'Wrong network',
    wrongNetwork: 'Your wallet is on another network. Switch to Arc to continue.',
    switchToArc: 'Switch to Arc',
    unreachableTitle: 'Could not reach Arc',
    unreachable: 'Check your connection and try again.',
    tryAgain: 'Try again',
    lastUpdated: (time: string) => `Last updated ${time}`,
    nairaNote: (when: string) => `Naira amounts are indicative, at the ${when} rate.`,
    rateCredit: 'Rates By Exchange Rate API',
    walletDisplay: 'Your wallet app may show USDC as ETH or with extra digits. The amounts in Earmark are correct.',
    loading: 'Loading',
  },

  config: {
    title: 'Earmark is not set up yet',
    body: 'This site is missing some settings:',
    fix: 'If you run this site, add them and deploy it again.',
  },

  wallet: {
    connect: 'Connect wallet',
    connecting: 'Connecting',
    choose: 'Choose your wallet',
    disconnect: 'Disconnect',
    none: 'To use Earmark, add a wallet such as MetaMask to this browser, then come back.',
    phone: 'On a phone, open this page in the MetaMask, OKX or Bitget app’s browser.',
    copyLink: 'Copy link',
    linkCopied: 'Link copied',
    rejected: 'You cancelled in your wallet. Nothing was sent.',
    gateTitle: 'Connect your wallet',
    gateBody: 'Earmark reads your pockets from Arc using your wallet’s address.',
  },

  landing: {
    headline: 'Money sent home, with a purpose.',
    lede: 'Fund labelled USDC pockets for school fees, food and rent. Your family pays from them under the rules you set.',
    seeLive: 'See a live pocket',
    stepsTitle: 'How it works',
    steps: [
      { title: 'Fund a pocket', body: 'Add USDC to a pocket with a purpose, such as Food or School fees.' },
      { title: 'Set the rules', body: 'Choose a weekly limit, who can be paid, and whether to lock it until a date.' },
      { title: 'Watch it spent', body: 'Every payment is final in under a second, and you see it straight away.' },
    ],
    cardCaption: 'A live pocket on Arc',
  },

  dashboard: {
    eyebrow: (n: number) => `Across ${n} ${n === 1 ? 'pocket' : 'pockets'}`,
    title: 'Your pockets',
    ledeFor: (total: string, name: string) => `${total} held for ${name}`,
    ledeAll: (total: string) => `${total} held in your pockets`,
    about: (naira: string) => `, about ${naira}`,
    shareFamily: 'Share family link',
    newPocket: 'New pocket',
    pockets: 'Pockets',
    waiting: 'Waiting for you',
    requestsBadge: (n: number) => `${n} ${n === 1 ? 'request' : 'requests'}`,
    nothingWaiting: 'Nothing is waiting for you.',
    activity: 'Activity',
    seeAll: 'See all',
    noActivity: 'Nothing has happened in your pockets yet.',
    emptyTitle: 'No pockets yet',
    emptyBody: 'Create a pocket for something your family needs, such as food or school fees.',
    emptyAction: 'Create a pocket',
    loading: 'Loading your pockets',
  },

  requests: {
    title: 'Requests',
    lede: 'Payments your family asked for. Approving pays them straight away.',
    emptyTitle: 'Nothing waiting',
    emptyBody: 'When someone asks for a payment above a pocket’s rules, it appears here.',
    approved: (amount: string) => `Approved and paid ${amount}`,
    declined: 'Request declined. The money stays in the pocket.',
    approveTitle: 'Approve and pay',
    approveButton: (amount: string) => `Approve and pay ${amount}`,
    declineHint: (label: string) => `The money stays in ${label}.`,
    declineTitle: 'Decline request',
  },

  activity: {
    title: 'Activity',
    lede: 'Every movement of money, newest first. Each one links to its receipt.',
    familyLede: 'Everything paid from your pockets, newest first.',
    loadOlder: 'Load older',
    emptyTitle: 'Nothing yet',
    emptyBody: 'Payments, money added and requests will appear here.',
    label: 'Activity',
    paid: (name: string) => `Paid ${name}`,
    addedByYou: 'You added money',
    addedBy: (name: string) => `Added by ${name}`,
    askedFor: (memo: string) => `Asked for “${memo}”`,
    askedToPay: (name: string) => `Asked to pay ${name}`,
    approvedMemo: (memo: string) => `Approved: “${memo}”`,
    approvedTo: (name: string) => `Approved payment to ${name}`,
    declinedMemo: (memo: string) => `Declined: “${memo}”`,
    declinedTo: (name: string) => `Declined payment to ${name}`,
    tookBack: 'You took money back',
    takenBack: 'Money taken back',
    feeCredit: 'Fee credit added',
    lockMoved: (date: string) => `Lock moved to ${date}`,
    created: 'Pocket created',
    payeeAdded: (name: string) => `Can pay ${name}`,
    payeeRemoved: (name: string) => `Can no longer pay ${name}`,
    limitChanged: (limit: string, each: string) => `Limit changed to ${limit} ${each}`,
    limitRequestOnly: 'Every payment is now a request',
    cancelledMemo: (memo: string) => `Withdrew the request: “${memo}”`,
    cancelledTo: (name: string) => `Withdrew the request to pay ${name}`,
    note: (memo: string) => `“${memo}”`,
    receipt: 'View receipt',
  },

  pocket: {
    back: 'Back to your pockets',
    inPocket: 'In this pocket',
    rulesTitle: 'Rules',
    rulePeriod: (limit: string, each: string, resets: string) => `Up to ${limit} ${each}. ${resets}.`,
    ruleRequestOnly: 'Every payment is a request.',
    rulePayeeOnly: (n: number) => `Approved payees only (${n})`,
    ruleAnyPayee: 'Can pay anyone',
    ruleLocked: (date: string) => `Locked until ${date}`,
    ruleNoLock: 'No lock. You can take money back at any time.',
    ruleFee: (amount: string, name: string) => `Keeps ${amount} in ${name}’s wallet for network fees`,
    ruleNoFee: 'No fee credit',
    ruleSpender: (name: string) => `${name} pays from this pocket`,
    addMoney: 'Add money',
    takeBack: 'Take money back',
    moveLock: 'Move lock date',
    share: 'Share pocket',
    payees: 'Approved payees',
    noPayees: 'This pocket can pay anyone.',
    lockTitle: (date: string) => `Locked until ${date}`,
    lockBody: 'You chose to keep this money here until then. You can move the date later, never earlier.',
    lockedHint: (date: string) => `You can take money back from ${date}.`,
    notFoundTitle: 'This pocket does not exist',
    notFoundBody: 'Check the link you were sent.',
    goHome: 'Go to Earmark',
    notYoursTitle: 'This is not your pocket',
    notYoursBody: 'Only the person who created it can manage it here. You can still view it.',
    viewPublic: 'View the pocket',
    loading: 'Loading the pocket',
  },

  add: {
    title: (label: string) => `Add money to ${label}`,
    amount: 'Amount',
    button: (amount: string) => `Add ${amount}`,
    enter: 'Enter an amount',
    allowStep: (amount: string) => `Allow Earmark to move ${amount} USDC`,
    step: 'Add money',
    done: (amount: string, label: string) => `Added ${amount} to ${label}`,
    coFunderTitle: 'This money becomes theirs to manage',
    coFunder: (name: string) => `${name} can take back anything in this pocket, including what you add.`,
    yourBalance: (amount: string) => `Your wallet holds ${amount}.`,
    notEnough: (amount: string) => `Your wallet holds only ${amount}.`,
  },

  takeBack: {
    title: (label: string) => `Take money back from ${label}`,
    amount: 'Amount',
    all: 'Take back all',
    to: 'Send to',
    toYou: 'Your wallet',
    button: (amount: string) => `Take back ${amount}`,
    confirmTitle: 'Take back everything?',
    confirmBody: (amount: string, name: string, label: string) =>
      `This moves all ${amount} back to your wallet. ${name} cannot pay from ${label} until you add money.`,
    done: (amount: string, label: string) => `Took back ${amount} from ${label}`,
    locked: (date: string) => `This pocket is locked until ${date}.`,
  },

  lock: {
    title: 'Move the lock date',
    field: 'New date',
    hint: (current: string) => `Later than ${current}, and at most two years from today.`,
    button: (date: string) => `Move lock to ${date}`,
    choose: 'Choose a date',
    done: (date: string) => `Lock moved to ${date}`,
    tooEarly: 'Choose a date later than the current lock.',
    tooLate: 'Choose a date within two years from today.',
  },

  create: {
    title: 'New pocket',
    back: 'Back to your pockets',
    nameLabel: 'Pocket name',
    nameHint: 'Your family sees this name. Name what it is for, such as Food, not a person.',
    nameAccents: 'Letters with accents take more space.',
    nameTooLong: 'Keep the name to 32 characters or fewer.',
    nameEmpty: 'Give the pocket a name.',
    iconLabel: 'Icon',
    hueLabel: 'Colour',
    whoTitle: 'Who can spend',
    whoLabel: 'Their address',
    whoHint: 'They pay from this pocket with this wallet.',
    savedNames: 'Saved names',
    nicknameLabel: 'Their name (only on this device)',
    nicknameHint: 'Only you see this name. It is never put on Arc.',
    allowanceTitle: 'Allowance',
    periodLabel: 'How often the limit resets',
    limitHint: (name: string, each: string) => `${name} can pay up to this much ${each} without asking.`,
    limitHintAnon: (each: string) => `They can pay up to this much ${each} without asking.`,
    limitEmpty: 'Enter a limit, or make every payment a request.',
    requestOnly: 'Every payment is a request',
    requestOnlyDesc: 'Nothing is paid without your approval.',
    rulesTitle: 'Rules',
    payeeOnly: 'Approved payees only',
    payeeOnlyDesc: 'Payments can only go to people you list. Anything else becomes a request.',
    payeeAddress: 'Payee address',
    payeeName: 'Payee name (only on this device)',
    addPayee: 'Add payee',
    removePayee: (name: string) => `Remove ${name}`,
    payeesMax: 'A pocket can have up to 10 approved payees.',
    payeesNeeded: 'Add at least one approved payee, or turn this rule off.',
    payeeDuplicate: 'This payee is already on the list.',
    lockLabel: 'Lock until a date',
    lockDesc: 'You cannot take money back before this date. You can move it later, never earlier.',
    lockDate: 'Locked until',
    lockHint: 'At most two years ahead.',
    lockInvalid: 'Choose a date after today and within two years.',
    feeTitle: 'Fee credit',
    feeLine: (amount: string, name: string) =>
      `Earmark keeps ${amount} in ${name}’s wallet for network fees, so they never need to buy anything else.`,
    feeLineAnon: (amount: string) =>
      `Earmark keeps ${amount} in their wallet for network fees, so they never need to buy anything else.`,
    feeOff: 'No fee credit. They pay network fees from their own wallet.',
    moreOptions: 'More options',
    fewerOptions: 'Fewer options',
    feeLabel: 'Fee credit',
    feeHint: 'Between $0.05 and $0.50, or $0 to turn it off. Top-ups are at most twice this each period.',
    feeInvalid: 'The fee credit can be $0, or between $0.05 and $0.50.',
    depositLabel: 'Money to add now',
    summaryTitle: 'Summary',
    summaryFor: (label: string, name: string) => `${label}, for ${name}`,
    summaryLimit: (limit: string, each: string) => `Up to ${limit} ${each} without asking`,
    summaryRequestOnly: 'Every payment needs your approval',
    summaryNoLimit: 'Limit not set yet',
    summaryPayees: (n: number) => `Approved payees only (${n})`,
    summaryAnyPayee: 'Can pay anyone',
    summaryLock: (date: string) => `Locked until ${date}`,
    summaryNoLock: 'No lock',
    summaryAdd: (amount: string) => `Adds ${amount} from your wallet`,
    summaryAddNothing: 'Adds nothing yet. You can add money later.',
    summaryFees: (amount: string) => `Network fees: about ${amount} in total`,
    button: 'Create pocket',
    fixErrors: 'Check the fields marked above.',
    allowStep: (amount: string) => `Allow Earmark to move ${amount} USDC`,
    createStep: 'Create the pocket',
    readyStep: 'Ready to share',
    doneTitle: 'Pocket created',
    doneBody: (name: string) =>
      `Send ${name} the family link. They open it in their wallet app to see the pocket and pay from it.`,
    familyLink: 'Family link',
    publicLink: 'Link anyone can view',
    copyFamily: 'Copy family link',
    share: 'Share',
    openPocket: 'Go to the pocket',
    done: 'Pocket created',
  },

  family: {
    greeting: (hour: number) => (hour < 12 ? 'Good morning' : hour < 18 ? 'Good afternoon' : 'Good evening'),
    title: 'Your pockets',
    ledeNamed: (name: string) => `${name} fills these pockets. Pay from them whenever you need to.`,
    lede: 'Pay from these pockets whenever you need to.',
    topUpTitle: (name: string, amount: string, label: string) => `${name} added ${amount} to ${label}`,
    topUpBody: (amount: string, period: string) => `You can spend ${amount} more ${period}.`,
    topUpAsk: 'Ask whenever you need a payment from it.',
    feeLine: (amount: string) =>
      `Fee credit: ${amount}. Network fees come out of your pockets. You never need to buy anything else.`,
    emptyTitle: 'Nothing here yet',
    emptyNamed: (name: string) => `${name} will add money soon.`,
    empty: 'Pockets made for this wallet will appear here.',
    loading: 'Loading your pockets',
    someone: 'Someone',
  },

  pay: {
    payTitle: (label: string) => `Pay from ${label}`,
    askTitle: (label: string) => `Ask from ${label}`,
    back: 'Back to your pockets',
    modeLabel: 'Pay or ask',
    modePay: 'Pay',
    modeAsk: 'Ask',
    amount: 'Amount',
    available: 'Available',
    payTo: 'Pay to',
    change: 'Change',
    chooseShort: 'Choose',
    choosePayee: 'Who are you paying?',
    otherAddress: 'Someone else',
    addressLabel: 'Their address',
    addressHint: 'Paste the full address. It starts with 0x.',
    saveName: 'Their name (only on this device)',
    noteLabel: 'Note (optional)',
    noteHint: 'Notes are public on Arc.',
    noteCount: (n: number) => `${n} of 64`,
    noteTooLong: 'Keep the note to 64 characters or fewer.',
    enterAmount: 'Enter an amount',
    choose: 'Choose who to pay',
    payButton: (amount: string) => `Pay ${amount}`,
    askButton: (amount: string) => `Ask for ${amount}`,
    askForApproval: 'Ask for approval',
    askLede: (name: string) => `${name} decides. If they say yes, the money goes straight to the person you chose.`,
    askLedeAnon: 'The pocket’s owner decides. If they say yes, the money goes straight to the person you chose.',
    overLimit: 'More than is available. Ask for approval instead.',
    notApproved: 'This pocket only pays approved people. Ask for approval instead.',
    requestOnly: 'Every payment from this pocket is a request.',
    paid: (amount: string, label: string) => `Paid ${amount} from ${label}`,
    asked: (amount: string, label: string) => `Asked for ${amount} from ${label}`,
    notYours: 'This wallet cannot pay from this pocket.',
  },

  notFound: {
    title: 'This page does not exist',
    body: 'Check the link, or start again from the home page.',
  },

  publicPage: {
    banner: 'You are viewing a pocket. Connect a wallet to act on it.',
    title: 'Pocket',
    createdBy: (name: string) => `Created by ${name}`,
    spentBy: (name: string) => `${name} pays from it`,
  },

  settings: {
    title: 'Settings',
    appearance: 'Appearance',
    themeOptions: [
      { value: 'system', label: 'System' },
      { value: 'light', label: 'Light' },
      { value: 'dark', label: 'Dark' },
    ],
    view: 'Show pockets you',
    viewOptions: [
      { value: 'sender', label: 'Fund' },
      { value: 'family', label: 'Spend' },
    ],
    viewHint: 'This wallet both funds pockets and spends from them.',
    names: 'Names on this device',
    namesHint: 'Names stay in this browser. They are never put on Arc.',
    noNames: 'No saved names yet.',
    addName: 'Save name',
    nameLabel: 'Name',
    addressLabel: 'Address',
    removeName: (name: string) => `Remove ${name}`,
    nameSaved: 'Name saved',
    wallet: 'Your wallet',
    familyLink: 'Family link',
    familyLinkHint: 'Send this to the person who pays from your pockets.',
    about: 'About',
    contract: 'Earmark on the Arc explorer',
    source: 'Source code',
    notConnected: 'No wallet connected.',
  },

  tx: {
    confirm: 'Confirm in your wallet',
    sending: 'Sending to Arc',
    final: 'Final',
    finalPayment: 'This cannot be reversed.',
    alreadyAllowed: 'Already allowed',
    failed: 'Did not go through',
    receipt: 'View receipt',
    close: 'Close',
    done: 'Done',
    stillWaiting: 'This is taking longer than usual. Check the receipt in a moment.',
  },

  errors: {
    notSponsor: 'Only the person who created this pocket can do that.',
    notSpender: 'Only the family member on this pocket can pay from it.',
    unknownPocket: 'This pocket does not exist.',
    invalidAddress: 'Earmark cannot pay this address. Check it and try again.',
    badAddressFormat: 'This is not a full Arc address. It should start with 0x and have 42 characters.',
    invalidAmount: 'Enter an amount above zero.',
    badLabel: 'The pocket name must be 1 to 32 characters.',
    memoTooLong: 'Keep the note to 64 characters or fewer.',
    badPeriod: 'The period must be between 1 and 31 days.',
    badLock: 'The lock date must be in the future and within two years.',
    lockNotExtended: 'You can only move the lock date later.',
    locked: (date: string) => `This pocket is locked until ${date}.`,
    overLimit: (amount: string, period: string) => `Only ${amount} is available ${period}. Ask for approval instead.`,
    insufficientBalance: (amount: string) => `The pocket only holds ${amount}.`,
    payeeNotApproved: 'This pocket only pays approved people. Ask for approval instead.',
    tooManyPayees: 'A pocket can have up to 10 approved payees.',
    tooManyPending: 'There are already 20 requests waiting.',
    notPending: 'This request has already been handled.',
    fuelOutOfRange: 'The fee credit can be at most $0.50.',
    badAppearance: 'Choose an icon and a colour for the pocket.',
    badToken: 'Earmark is set up with the wrong kind of money. Nothing was sent.',
    reentrant: 'That did not go through. Nothing was sent. Try again.',
    transferFailed: 'USDC could not be moved. Nothing was sent.',
    tooLarge: 'That amount is too large.',
    walletRejected: 'You cancelled in your wallet. Nothing was sent.',
    wrongNetwork: 'Your wallet is on another network. Switch to Arc to continue.',
    unreachable: 'Could not reach Arc. Check your connection and try again.',
    complianceSent: 'USDC compliance rules stopped this payment. The network fee was still charged.',
    compliancePreflight: 'USDC compliance rules block this address. Nothing was sent.',
    walletShort: 'Your wallet does not hold enough USDC for this.',
    feeShort: 'Your wallet needs a little more USDC to cover the network fee.',
    noWallet: 'Connect a wallet to continue.',
    failedOnArc: 'This did not go through on Arc. The network fee was still charged.',
    unknown: 'That did not go through. Try again in a moment.',
  },

  toast: {
    copied: 'Link copied',
    addressCopied: 'Address copied',
    dismiss: 'Dismiss',
  },

  icons: {
    'graduation-cap': 'School fees',
    'bowl-food': 'Food',
    'house-line': 'Rent',
    'first-aid-kit': 'Emergency',
    lightning: 'Electricity',
    'device-mobile': 'Airtime and data',
    bus: 'Transport',
    'shopping-bag': 'Market',
    'hand-heart': 'Gifts and giving',
    'piggy-bank': 'Savings',
  } as Record<string, string>,

  hues: {
    palm: 'Palm',
    sky: 'Sky',
    clay: 'Clay',
    teal: 'Teal',
    plum: 'Plum',
    olive: 'Olive',
  } as Record<string, string>,
} as const;
